// Loader for the gold-ruleset-derived catalog (spec019 rework, 2026-08-01).
// Generated by frontend/scripts/build_gold_catalog.py -- re-run that script after any
// change to storage/rules/gold/, do not hand-edit goldCatalog.json.
import raw from "./goldCatalog.json";
import type { Check, Block, Route } from "../lib/types";

const data = raw as unknown as { checks: Check[]; blocks: Block[]; routes: Route[] };

export const GOLD_CHECKS: Check[] = data.checks;
export const GOLD_BLOCKS: Block[] = data.blocks;
export const GOLD_ROUTES: Route[] = data.routes;
