"""
verify_report_accuracy.py -- does the QC ENGINE'S VERDICT (and, by extension,
output/QC_Engine_Results_for_Kayla_Review.xlsx, which is a straight export of
that same verdict) match the reality of the 5 synthetic loans in demo/syn/?

verify_against_defects.py (this directory) already answers a narrower
question: does field EXTRACTION reproduce the 25 known-defect values exactly?
That's necessary but not sufficient -- a field can extract correctly and the
ENGINE can still fail to flag it (a false auto-clear: a real problem waved
through) or flag a clean condition that isn't one (a false positive: reviewer
trust erodes, "auto-clear the obvious" stops meaning anything). This script
answers that verdict-level question directly, by running every loan through
the exact same defects_ruleset_for() + qc_engine.run() pipeline
export_qc_results_xlsx.py uses, and checking:

  1. RECALL on known defects -- of the checks wired to one of the 25 planted
     defects (20 of 25; see ruleset_defects.py's own docstring for which 5
     have no check-kind yet), did the engine's verdict actually surface as
     something a reviewer would see (FAIL / WARNING / NEEDS_REVIEW / FLAG),
     or did it silently PASS / go NOT_APPLICABLE -- a false auto-clear of a
     real, planted defect?

  2. FALSE POSITIVES on clean conditions -- of every OTHER check that ran on
     a given loan (i.e. not tied to one of that loan's own planted defects),
     did it correctly PASS / NOT_APPLICABLE, or did it incorrectly surface as
     an exception on a condition that was never planted as a defect?

  3. REPORT FIDELITY -- does the actual xlsx file on disk
     (output/QC_Engine_Results_for_Kayla_Review.xlsx) match a fresh live run
     right now, cell for cell on (Loan ID, Check ID) -> Verdict? Catches the
     report silently going stale after an engine/ruleset code change (the
     xlsx is a one-off export, not regenerated by any test suite -- see its
     own script's docstring).

Coverage is explicitly bounded, and that bound is reported, not hidden:
  - Only 20/25 known defects have a wired check at all (5 are doc-vs-doc
    comparisons with no check-kind built yet -- ruleset_defects.py defers
    these to 003c or a new kind). Recall is computed over the 20, and the 5
    untestable ones are listed by name in the output, never silently dropped.
  - This says nothing about extraction accuracy on real (non-synthetic)
    lender documents, or about whether the wired checks' operators/thresholds
    faithfully represent the real AMQ condition text in demo/rules/*.xlsx --
    that is a separate, largely manual rule-fidelity question (a handful of
    checks are annotated in from_docs/README.md as exact-AMQ-text matches;
    most are not yet cross-checked against the AMQ workbooks at all).

Python 3.9 compatible.
"""
from __future__ import annotations

import json
import os
import sys
from typing import Any, Dict, List, Optional, Tuple

HERE = os.path.dirname(os.path.abspath(__file__))
P0_DIR = os.path.dirname(os.path.dirname(HERE))
REPO_ROOT = os.path.dirname(P0_DIR)
sys.path.insert(0, HERE)
sys.path.insert(0, P0_DIR)

from qc_engine import run  # noqa: E402
from build_fixtures import build_all_fixtures  # noqa: E402
from fixture_loader import load_canonical_loan  # noqa: E402
from fixtures.ruleset_defects import defects_ruleset_for  # noqa: E402

MANIFEST_PATH = os.path.join(HERE, "defect_manifest.json")
REPORT_XLSX_PATH = os.path.join(REPO_ROOT, "output", "QC_Engine_Results_for_Kayla_Review.xlsx")

# A verdict a human reviewer would actually SEE as an exception -- i.e. NOT a
# silent auto-clear. FLAG is included because chk-def-fha-case-number's
# doc-vs-system mismatch is RECONCILE-phase by design and correctly verdicts
# FLAG, never FAIL (engine.py's own informational-flag design; see
# ruleset_defects.py Bucket D docstring) -- treating that as "missed" would
# be testing the wrong thing.
SURFACED_STATUSES = frozenset({"FAIL", "WARNING", "NEEDS_REVIEW", "FLAG"})
CLEAN_STATUSES = frozenset({"PASS", "NOT_APPLICABLE"})

# Ground-truth linkage: (loan_id, defect_number) -> check_id(s) wired to that
# defect, hand-authored directly from ruleset_defects.py's own module
# docstring (its 4-bucket enumeration) and defect_manifest.json's field
# names -- not derived by string-matching field_name, because 2 of the 21
# checks (Bucket C) evaluate a BUILD-TIME-DERIVED field
# (appraisal_staleness_days / nov_days_after_closing) that never appears
# literally in the manifest, and the USDA PITI/DTI manifest entry maps to TWO
# checks (its field_name and its compare_field_name each get their own
# Check). Kept explicit and hand-verified rather than "clever" so a
# manifest/ruleset drift shows up as this script failing to find an entry,
# not as a silently-wrong mapping.
DEFECT_TO_CHECK_IDS: Dict[Tuple[str, int], List[str]] = {
    ("2025-0917-001", 3): ["chk-def-large-deposit"],
    ("2025-0917-001", 5): ["chk-def-appraisal-comp-distance"],
    ("2025-1004-FHA-002", 1): ["chk-def-hud92900a-signed"],
    ("2025-1004-FHA-002", 2): ["chk-def-fha-case-number"],
    ("2025-1004-FHA-002", 3): ["chk-def-gift-funds-documented"],
    ("2025-1004-FHA-002", 4): ["chk-def-lead-paint-cert"],
    ("2025-1004-FHA-002", 5): ["chk-def-fha-amendatory-clause"],
    ("2025-1108-VA-003", 1): ["chk-def-nov-date-order"],
    ("2025-1108-VA-003", 2): ["chk-def-arm-preloan-disclosure"],
    ("2025-1108-VA-003", 3): ["chk-def-termite-inspection"],
    ("2025-1108-VA-003", 4): ["chk-def-lead-paint-disclosure"],
    ("2025-1108-VA-003", 5): ["chk-def-va-residual-income"],
    ("2025-1215-FRD-004", 3): ["chk-def-mortgage-late-payments"],
    ("2025-1215-FRD-004", 4): ["chk-def-appraisal-staleness"],
    ("2025-1215-FRD-004", 5): ["chk-def-self-employed-pl-bs"],
    ("2025-1122-USDA-005", 1): ["chk-def-usda-household-income"],
    ("2025-1122-USDA-005", 2): ["chk-def-usda-property-eligibility"],
    ("2025-1122-USDA-005", 3): ["chk-def-usda-piti-ratio", "chk-def-usda-dti-ratio"],
    ("2025-1122-USDA-005", 4): ["chk-def-well-septic-test"],
    ("2025-1122-USDA-005", 5): ["chk-def-site-value-justification"],
}

# The 5 known defects with no wired check at all (genuine doc-vs-doc
# comparisons; see ruleset_defects.py module docstring) -- listed explicitly
# so they're reported as an honest coverage gap, never silently absent from
# the recall denominator.
UNTESTABLE_DEFECTS: List[Tuple[str, int, str]] = [
    ("2025-0917-001", 1, "employment_start_date_1003 vs VOE (doc-vs-doc, no check-kind yet)"),
    ("2025-0917-001", 2, "title_vesting_1003 vs title commitment (doc-vs-doc, no check-kind yet)"),
    ("2025-0917-001", 4, "liability_disclosed_on_1003 vs credit report (doc-vs-doc, no check-kind yet)"),
    ("2025-1215-FRD-004", 1, "loan_purpose_1003 vs closing disclosure (doc-vs-doc, no check-kind yet)"),
    ("2025-1215-FRD-004", 2, "cd_payoff_amount vs payoff statement (doc-vs-doc, no check-kind yet)"),
]


def _load_manifest() -> Dict[str, Any]:
    with open(MANIFEST_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def _run_all_loans() -> Dict[str, Any]:
    """Returns {loan_id: {"results_by_check_id": {...}, "loan": CanonicalLoan}}."""
    written = build_all_fixtures()
    out = {}
    for _loan_folder, path in sorted(written.items()):
        loan = load_canonical_loan(path)
        rs = defects_ruleset_for(loan)
        res = run(loan, rs)
        out[loan.loan_id] = {
            "results_by_check_id": {r.check_id: r for r in res.results},
            "checked_ids": {c.id for c in rs.checks},
            "loan": loan,
        }
    return out


# The 2 property-age-gated checks (see ruleset_defects.py's own docstring,
# "PROPERTY-AGE gate") apply whenever year_built_appraisal is unknown OR
# < 1978 -- a deliberately conservative design (absence of contrary evidence
# should never silently clear a compliance check). That conservatism has a
# real, quantifiable precision cost this script surfaces rather than hides:
# a loan with NO planted lead-paint defect at all can still show one or both
# of these checks as an "exception" purely because its appraisal never
# recorded a build year, or because the gate itself doesn't distinguish
# "pre-1978" from the narrower real HUD trigger for the completion-cert
# check specifically (a peeling/chipping-paint finding, not bare pre-1978
# construction -- defect_manifest.json's own loan-02 defect description says
# "Peeling paint flagged," not merely "built before 1978"). Annotated here,
# not fixed -- changing the gate is an engine-design decision outside this
# test's scope, and the conservative default may well be the intended
# tradeoff (a missed lead-paint compliance issue is a worse failure mode
# than an extra reviewer glance).
_PROPERTY_AGE_GATED_CHECK_IDS = {"chk-def-lead-paint-cert", "chk-def-lead-paint-disclosure"}


def _false_positive_note(check_id: str, loan) -> str:
    if check_id not in _PROPERTY_AGE_GATED_CHECK_IDS:
        return ""
    year_built = loan.get("year_built_appraisal").doc
    if year_built is None:
        return ("KNOWN, DOCUMENTED CAUSE: year_built_appraisal is unknown for this loan -- the "
                "property-age gate conservatively applies both lead-paint checks whenever build "
                "year can't be confirmed, per ruleset_defects.py's own design (absence of contrary "
                "evidence should never silently clear a compliance check). Not an engine bug.")
    return ("LIKELY GATE IMPRECISION: property is pre-1978 ({0}), which correctly triggers the "
            "lead-paint DISCLOSURE check -- but the COMPLETION-CERT check's real HUD trigger is a "
            "peeling/chipping-paint finding specifically, not bare pre-1978 construction, and the "
            "gate doesn't check for that finding. Worth a second look at the gate logic, not just "
            "the data.").format(year_built)


def _score_recall(manifest: Dict[str, Any], runs: Dict[str, Any]) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]]]:
    """Returns (caught, missed) -- one row per wired known defect."""
    caught, missed = [], []
    for defect in manifest["defects"]:
        key = (defect["loan_id"], defect["defect_number"])
        check_ids = DEFECT_TO_CHECK_IDS.get(key)
        if check_ids is None:
            continue  # untestable defect, handled separately
        run_data = runs.get(defect["loan_id"])
        for check_id in check_ids:
            row = {
                "loan_id": defect["loan_id"],
                "defect_number": defect["defect_number"],
                "description": defect["description"],
                "check_id": check_id,
            }
            result = run_data["results_by_check_id"].get(check_id) if run_data else None
            if result is None:
                row["actual_status"] = "(check did not run on this loan -- gated out)"
                missed.append(row)
            elif result.status in SURFACED_STATUSES:
                row["actual_status"] = result.status
                caught.append(row)
            else:
                row["actual_status"] = result.status
                missed.append(row)
    return caught, missed


def _score_false_positives(manifest: Dict[str, Any], runs: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Every check that ran on a loan but isn't tied to one of THAT loan's own
    planted defects should resolve PASS/NOT_APPLICABLE. Anything else is a
    false positive -- the engine crying wolf on a condition nobody planted as
    a defect."""
    defect_check_ids_by_loan: Dict[str, set] = {}
    for defect in manifest["defects"]:
        key = (defect["loan_id"], defect["defect_number"])
        for cid in DEFECT_TO_CHECK_IDS.get(key, []):
            defect_check_ids_by_loan.setdefault(defect["loan_id"], set()).add(cid)

    false_positives = []
    for loan_id, run_data in runs.items():
        defect_check_ids = defect_check_ids_by_loan.get(loan_id, set())
        for check_id, result in run_data["results_by_check_id"].items():
            if check_id in defect_check_ids:
                continue
            if result.status not in CLEAN_STATUSES:
                false_positives.append({
                    "loan_id": loan_id,
                    "check_id": check_id,
                    "actual_status": result.status,
                    "message": result.message,
                    "note": _false_positive_note(check_id, run_data["loan"]),
                })
    return false_positives


def _score_report_fidelity(runs: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Compares the live run's (Loan ID, Check ID) -> Verdict against what's
    actually recorded in the xlsx on disk right now. Empty list = the report
    is not stale relative to current engine/ruleset code."""
    if not os.path.exists(REPORT_XLSX_PATH):
        return [{"error": "report xlsx not found at {0}".format(REPORT_XLSX_PATH)}]

    import openpyxl
    wb = openpyxl.load_workbook(REPORT_XLSX_PATH, data_only=True)
    ws = wb["Check Detail"]
    header = [c.value for c in next(ws.iter_rows(min_row=1, max_row=1))]
    loan_id_idx = header.index("Loan ID")
    check_id_idx = header.index("Check ID")
    verdict_idx = header.index("Verdict")

    drift = []
    seen_in_xlsx = set()
    for row in ws.iter_rows(min_row=2, values_only=True):
        loan_id, check_id, xlsx_verdict = row[loan_id_idx], row[check_id_idx], row[verdict_idx]
        seen_in_xlsx.add((loan_id, check_id))
        run_data = runs.get(loan_id)
        live_result = run_data["results_by_check_id"].get(check_id) if run_data else None
        live_verdict = live_result.status if live_result else "(missing from live run)"
        if live_verdict != xlsx_verdict:
            drift.append({
                "loan_id": loan_id, "check_id": check_id,
                "xlsx_verdict": xlsx_verdict, "live_verdict": live_verdict,
            })

    # Also catch the reverse: a check the live run produces that's absent
    # from the xlsx entirely (report under-counting).
    for loan_id, run_data in runs.items():
        for check_id in run_data["results_by_check_id"]:
            if (loan_id, check_id) not in seen_in_xlsx:
                drift.append({
                    "loan_id": loan_id, "check_id": check_id,
                    "xlsx_verdict": "(missing from xlsx)",
                    "live_verdict": run_data["results_by_check_id"][check_id].status,
                })
    return drift


def main() -> int:
    manifest = _load_manifest()
    runs = _run_all_loans()

    caught, missed = _score_recall(manifest, runs)
    false_positives = _score_false_positives(manifest, runs)
    drift = _score_report_fidelity(runs)

    wired_total = len(caught) + len(missed)

    print("=" * 78)
    print("QC ENGINE / REPORT ACCURACY TEST")
    print("Ground truth: {0} ({1} planted defects across 5 synthetic loans)".format(
        os.path.relpath(MANIFEST_PATH, REPO_ROOT), len(manifest["defects"])))
    print("Report under test: {0}".format(os.path.relpath(REPORT_XLSX_PATH, REPO_ROOT)))
    print("=" * 78)

    print("\n--- 1. RECALL on known, wired defects ({0}/{1} check-instances) ---".format(
        wired_total, wired_total))
    for row in caught:
        print("  [CAUGHT] {0} defect#{1} -> {2} ({3})".format(
            row["loan_id"], row["defect_number"], row["check_id"], row["actual_status"]))
    for row in missed:
        print("  [MISSED] {0} defect#{1} -> {2} ({3}) -- FALSE AUTO-CLEAR of: {4}".format(
            row["loan_id"], row["defect_number"], row["check_id"], row["actual_status"], row["description"]))
    recall = (len(caught) / wired_total) if wired_total else float("nan")
    print("  RECALL: {0}/{1} = {2:.1%}".format(len(caught), wired_total, recall))

    print("\n--- 2. Coverage gap: defects with NO wired check ({0}) ---".format(
        len(UNTESTABLE_DEFECTS)))
    for loan_id, defect_number, desc in UNTESTABLE_DEFECTS:
        print("  [UNTESTABLE] {0} defect#{1} -- {2}".format(loan_id, defect_number, desc))
    print("  These do not count toward recall above -- they cannot fail or pass this test;")
    print("  the report has NO opinion on them at all (silent, not wrong -- but silent).")

    print("\n--- 3. FALSE POSITIVES on non-defect (clean) conditions ({0}) ---".format(
        len(false_positives)))
    for row in false_positives:
        print("  [FALSE POSITIVE] {0} {1} -> {2}: {3}".format(
            row["loan_id"], row["check_id"], row["actual_status"], row["message"]))
        if row["note"]:
            print("      -> {0}".format(row["note"]))
    if not false_positives:
        print("  none -- every non-defect check on all 5 loans correctly resolved PASS/NOT_APPLICABLE.")

    print("\n--- 4. REPORT FIDELITY vs. live engine run ({0} drift rows) ---".format(len(drift)))
    for row in drift:
        if "error" in row:
            print("  [ERROR] {0}".format(row["error"]))
        else:
            print("  [DRIFT] {0} {1}: xlsx={2!r} live={3!r}".format(
                row["loan_id"], row["check_id"], row["xlsx_verdict"], row["live_verdict"]))
    if not drift:
        print("  none -- the xlsx on disk matches a fresh live run exactly.")

    print("\n" + "=" * 78)
    print("SUMMARY: recall {0}/{1} ({2:.1%}) | {3} untestable (no check exists) | "
          "{4} false positives | {5} report-drift rows".format(
              len(caught), wired_total, recall, len(UNTESTABLE_DEFECTS),
              len(false_positives), len(drift)))
    print("=" * 78)

    ok = (len(missed) == 0) and (len(false_positives) == 0) and (len(drift) == 0)
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
